# Generated by Django 3.0.7 on 2020-10-22 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201015_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='id',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_ID',
            field=models.CharField(help_text='Squirrel_ID', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Format doesnt comply', regex='[0-9]+[A-Z]-[A-Z]{2}-[0-9]{4}-[0-9]{2}')]),
        ),
    ]
